version: '3.8'

networks:
  app-network:
    driver: bridge

services:
  db:
    image: postgres:15
    container_name: postgres_db_2ch
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: 2ch_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_2ch
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db
    networks:
      - app-network

  2ch.webapi:
    image: 2chwebapi
    container_name: 2chwebapi
    depends_on:
      - db
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=2ch_db;Username=admin;Password=root
    ports:
      - "8080:90"
    networks:
      - app-network

volumes:
  db_data:
  pgadmin_data: